[package]
name = "UniSim"
version = "0.1.0"
edition = "2024"

[features]
default = []
debug = []
cuda = []

[dev-dependencies]
csv = "1.3.1"


[dependencies]
paste = "1.0.15"
rand = "0.9.2"
ndarray = "0.16.1"
libc = "0.2.176"
